### ISSUE TITLE
last version error

### ISSUE THREAD

**Issue by john-whick-13** [Nico-Curti/pyhide#3]
i use the last version but got this error 

D:\PythonRAT-final\client>python -m pyhide --input myfile.py --variable --function --class --pkg --num --str --output encCustomer.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mobco-2031\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhide.py", line 287, in <module>
    image = image_from_url(image_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mobco-2031\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhide.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mobco-2031\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhide.py", line 53, in image_from_url
    raise RuntimeError('connection failed with status code {}'.format(response.status_code))
RuntimeError: connection failed with status code 403

**Comment by Nico-Curti** [comment]
Your error is related to an HTML request error (403 HTTP Forbidden ) that is not related to my package.
In your code there should be a mismatch between my package and [this one](https://pypi.org/project/pyhide/).
Probably you have installed the package with pip, while I provide the installation only via setup!

You can uninstall pyhide via pip and force the installation of my package via setup

**Comment by john-whick-13** [comment]
1- i removed pyhide by `pip uninstall pyhide `

2- git clone it a gain 

3- inside the pyhide folder make `gitpull `

4 - then use this command to install it `python -m pip install --editable . --user`

5- use this command `pyhide --input .\customer.py --variable --function --class --pkg --num --str`

6- got the same error `Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mobco-2031\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\pyhide.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mobco-2031\Downloads\pyhide\pyhide\__main__.py", line 169, in main
    obf_code = obf(code)
               ^^^^^^^^^
  File "C:\Users\Mobco-2031\Downloads\pyhide\pyhide\obfuscator.py", line 138, in __call__
    var_names = get_all_list_of_variable_names(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mobco-2031\Downloads\pyhide\pyhide\_encoder.py", line 187, in get_all_list_of_variable_names
    elif isinstance(node, ast.Attribute) and node.value.id == 'self':
                                             ^^^^^^^^^^^^^
AttributeError: 'Attribute' object has no attribute 'id'`

**Comment by john-whick-13** [comment]
also i test it on kali linux and it give me the same error

**Comment by Nico-Curti** [comment]
You are probably working with a too advanced script for this naive package.
I'm still working on this package and there are many code branches that I have ignored yet.

According to your error, my idea is that there is a nested call attribute in your code which is not supported yet by the package.
You can try to split your code in simpler lines and check if it works properly.

In the [last commit](https://github.com/Nico-Curti/pyhide/commit/a652281b21f94e28d033bb270c1f429c38e59353) I tried to check the error that you pointed out, but without your original code I cannot reproduce the error correctly.

**Comment by john-whick-13** [comment]
thanks a lot its working for me , hope more updates , hope good career for you , really thanks
